### ISSUE TITLE
Ensure Dependabot is working

### ISSUE THREAD

**Issue by spikymonkey** [pivotal-cf/java-cfenv#155]
We would like Dependabot to be creating dependency bump PRs for our projects.

A little while ago we updated the build to store dependency version properties (e.g. `springBootVersion`) in the gradle.properties file.

That seemed like a nice idea at the time, but it seems like Dependabot doesn't like it. We may need to move back to storing these in `ext { ... }` or some other format that Dependabot can handle. Dependabot does not yet understand Gradle 7's new versioning features so we can't use those unfortunately.

**Comment by elefeint** [comment]
Chiming in from _spring-cloud-gcp_ here -- Dependabot got overly excited and [upgraded us from 2.3.0 to 2.4.0](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/524), but it does not look like this release is out yet. 

It seems that the artifacts made their way into https://repo.spring.io/release/io/pivotal/cfenv/java-cfenv/2.4.0 at some point today, and then got deleted later.

I'll revert the change in our repo, but I wanted to let you know that whatever you did worked well as far as this issue is concerned.

**Comment by royclarkson** [comment]
Sorry for the confusion here. We've been improving the CI release process and that involved a few test runs to Spring artifactory. Unfortunately we still have a few bits to polish for the sync to maven central so you may see it happen again. Thanks for letting us know dependabot is so diligent in other projects.

**Comment by abelsromero** [comment]
@elefeint v2.4.0 has been release, now for sure. Sorry for the inconvenience.

**Comment by elefeint** [comment]
Thank you!

**Comment by abelsromero** [comment]
Changes have been aplied https://github.com/pivotal-cf/java-cfenv/pull/158, we can keep this open "in progress" waiting to see if dependabot reports on new Spring Boot version to confirm it works.

**Comment by abelsromero** [comment]
This PR https://github.com/pivotal-cf/java-cfenv/pull/163 validates the changes applied.
